import Mathlib

open Subgroup

-- Hint: Exercise 2.2.9
theorem subgroup_generated_by_commuting_elements_is_abelian
  -- "Fix G, a, b, H"
  (G : Type*) [Group G] (a b : G)
  -- "condition: G is a group, a, b are elements of G"
  -- "H is the subgroup generated by a, b"
  -- (We define H implicitly as Subgroup.closure {a, b})
  :
  -- "Show if a b=b a, then H is an abelian group."
  (h_comm : a * b = b * a) → -- "Assume ab=ba"
  ∀ (g h : Subgroup.closure {a, b}), g * h = h * g :=
by
  -- "Assume ab=ba" (This is now an argument)
  intro h_comm_proof g h
  -- To show g * h = h * g as subgroup elements, we show equality as elements of G
  apply Subtype.ext
  -- "Obtain i, j, k, l"
  -- "condition: i,j,k,l are integers, g=a^ib^j, h = a^kb^l"
  -- "reason: H is the subgroup generated by commuting elements a, b"
  have hg : ∃ (i j : ℤ), (g : G) = a ^ i * b ^ j := by sorry
  have hh : ∃ (k l : ℤ), (h : G) = a ^ k * b ^ l := by sorry
  rcases hg with ⟨i, j, hg_eq⟩
  rcases hh with ⟨k, l, hh_eq⟩

  -- "CalculationChain"
  calc
    -- "initial_expression: gh" (as elements of G)
    (g : G) * (h : G)
    -- "operator: ="
    -- "expression: a^ib^ja^kb^l"
    -- "reason: null"
    = (a ^ i * b ^ j) * (a ^ k * b ^ l) := by rw [hg_eq, hh_eq]
    -- "operator: ="
    -- "expression: a^kb^la^ib^j"
    -- "reason: a and b commute"
    _ = (a ^ k * b ^ l) * (a ^ i * b ^ j) := by sorry
    -- "operator: ="
    -- "expression: hg"
    -- "reason: null"
    _ = (h : G) * (g : G) := by rw [hh_eq, hg_eq]
  -- "Have H is abelian" (This is the goal we just proved)
